fix #1645 adding until 12 indent levels
eclipse-ee4j/jaxb-ri pull request #1747
Opened 2023-09-26 22:29 UTC by antoniosanct

@lukasj 
It's not the best solution, but fixes 8 indentation leves, adding until 12.
Please rate this PR if you think it is appropriate to solve the issue.
Regards,
Antonio.

2024-07-20 13:42 UTC, laeubi commented on jaxb-ri/runtime/impl/src/main/java/org/glassfish/jaxb/runtime/v2/runtime/output/IndentingUTF8XmlOutput.java
> +    private static final int MAX_DEPTH = 12;
```suggestion
    private static final int MAX_DEPTH = Integer.getInteger("jaxb.ri.max_depth", 12);
```

2024-07-20 13:43 UTC, laeubi commented
This will fix https://github.com/eclipse-ee4j/jaxb-ri/issues/1645 is there any reason to not proceed on this?

2024-08-27 15:42 UTC, tfroment commented
Hi any news on this one?

2025-08-08 16:00 UTC, zunzaij commented
It does **not** fix the problem, it just chages the length of the used buffer.
The real error was even copied, replacing only the number with a variable.
To fix the error, only line 116 needs to be corrected.

A longer explanation is included in the original issue.
https://github.com/eclipse-ee4j/jaxb-ri/issues/1645#issuecomment-3167962780

Added fix as pull:
https://github.com/eclipse-ee4j/jaxb-ri/pull/1847#issue-3304625247

2025-08-08 18:04 UTC, zunzaij requested changes
Increasing the length of the buffer used doesn't solve the problem. Defining the buffer size via external parameters also poses a certain risk. The maximum integer size would be 2G, while with a 4-byte unitLen, 8G of RAM is reserved as a buffer.

It is a false assumption that a limit exists at all and a trivial error in line 116 that only needs to be corrected.

2025-08-08 20:17 UTC, closed without merging

2025-08-08 20:17 UTC, antoniosanct commented
@zunzaij

I like your solution more than I've proposed. I prefer to close my PR and merge your PR ASAP.

Thanks a lot! Regards,
Antonio.